### ISSUE TITLE
can't install v1.8.2 gem on mac

### ISSUE THREAD

**Issue by bikeonastick** [flori/json#239]
first while trying to install via bundle install, it's dying:

```
rt@rlbox:~/Development/mobile/appium-sample/sample-code/examples/ruby (master=)$ gem install json -v 1.8.2
Building native extensions.  This could take a while...
ERROR:  Error installing json:
        ERROR: Failed to build gem native extension.

            /Users/rt/.rubies/ruby-2.1.3/bin/ruby extconf.rb
            /Users/rt/.rubies/ruby-2.1.3/bin/ruby: invalid option -2  (-h will show valid options) (RuntimeError)

            extconf failed, exit code 1

            Gem files will remain installed in /Users/rt/.gem/ruby/2.1.3/gems/json-1.8.2 for inspection.
            Results logged to /Users/rt/.gem/ruby/2.1.3/extensions/x86_64-darwin-14/2.1.0-static/json-1.8.2/gem_make.out
```
then i went to the gem directory and tried to just run rake and, there, it seems to die while trying to run the tests.

```
rt@rlbox:~/.gem/ruby/2.1.3/gems/json-1.8.2$ rake --trace
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
Bundler version 1.9.2
fatal: Not a git repository (or any of the parent directories): .git
** Invoke default (first_time)
** Invoke clean (first_time)
** Execute clean
** Invoke gemspec (first_time)
** Invoke gemspec_pure (first_time)
** Invoke version (first_time)
** Execute version
Writing version information for 1.8.2
** Execute gemspec_pure
** Invoke gemspec_ext (first_time)
** Invoke version
** Execute gemspec_ext
** Execute gemspec
** Invoke test (first_time)
** Execute test
env JSON=pure bundle exec rake test_pure                                                             ruby: invalid option -2  (-h will show valid options) (RuntimeError)
rake aborted!
Command failed with status (1): [env JSON=pure bundle exec rake test_pure...]
/Users/rt/.gem/ruby/2.1.3/gems/rake-10.4.2/lib/rake/file_utils.rb:66:in `block in create_shell_runner'
/Users/rt/.gem/ruby/2.1.3/gems/rake-10.4.2/lib/rake/file_utils.rb:57:in `call'
/Users/rt/.gem/ruby/2.1.3/gems/rake-10.4.2/lib/rake/file_utils.rb:57:in `sh'
/Users/rt/.gem/ruby/2.1.3/gems/rake-10.4.2/lib/rake/file_utils_ext.rb:37:in `sh'
/Users/rt/.gem/ruby/2.1.3/gems/json-1.8.2/Rakefile:189:in `block in <top (required)>'
/Users/rt/.gem/ruby/2.1.3/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'                            /Users/rt/.gem/ruby/2.1.3/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/Users/rt/.gem/ruby/2.1.3/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/Users/rt/.gem/ruby/2.1.3/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/Users/rt/.gem/ruby/2.1.3/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain' /Users/rt/.rubies/ruby-2.1.3/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/Users/rt/.gem/ruby/2.1.3/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/rt/.gem/ruby/2.1.3/gems/rake-10.4.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/Users/rt/.gem/ruby/2.1.3/gems/rake-10.4.2/lib/rake/task.rb:199:in `each'                            /Users/rt/.gem/ruby/2.1.3/gems/rake-10.4.2/lib/rake/task.rb:199:in `invoke_prerequisites'
/Users/rt/.gem/ruby/2.1.3/gems/rake-10.4.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/Users/rt/.rubies/ruby-2.1.3/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/Users/rt/.gem/ruby/2.1.3/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/rt/.gem/ruby/2.1.3/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/Users/rt/.gem/ruby/2.1.3/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/Users/rt/.gem/ruby/2.1.3/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/rt/.gem/ruby/2.1.3/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/Users/rt/.gem/ruby/2.1.3/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/Users/rt/.gem/ruby/2.1.3/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/Users/rt/.gem/ruby/2.1.3/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/Users/rt/.gem/ruby/2.1.3/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/Users/rt/.gem/ruby/2.1.3/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/rt/.gem/ruby/2.1.3/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/Users/rt/.gem/ruby/2.1.3/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/Users/rt/.gem/ruby/2.1.3/bin/rake:23:in `load'
/Users/rt/.gem/ruby/2.1.3/bin/rake:23:in `<main>'
Tasks: TOP => default => test_pure
```

struggling to find out what the problem is on my machine. i would expect to see many more people hitting this issue if it were a general problem.

**Comment by bikeonastick** [comment]
same behavior different mac:

```
gem install json
Fetching: json-1.8.2.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing json:
	ERROR: Failed to build gem native extension.

    /Users/roberttomb/.rubies/ruby-2.0.0-p451/bin/ruby extconf.rb
/Users/roberttomb/.rubies/ruby-2.0.0-p451/bin/ruby: invalid option -2  (-h will show valid options) (RuntimeError)


Gem files will remain installed in /Users/roberttomb/.gem/ruby/2.0.0/gems/json-1.8.2 for inspection.
Results logged to /Users/roberttomb/.gem/ruby/2.0.0/gems/json-1.8.2/ext/json/ext/generator/gem_make.out
```
then i went to the install directory and ran `rake`

```
rake
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
Bundler version 1.7.3
fatal: Not a git repository (or any of the parent directories): .git
Writing version information for 1.8.2
env JSON=pure bundle exec rake test_pure
Your Gemfile lists the gem permutation (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
Your Gemfile lists the gem sdoc (~> 0.3.16) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
Your Gemfile lists the gem json (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
ruby: invalid option -2  (-h will show valid options) (RuntimeError)
rake aborted!
Command failed with status (1): [env JSON=pure bundle exec rake test_pure...]
/Users/roberttomb/.gem/ruby/2.0.0/gems/json-1.8.2/Rakefile:189:in `block in <top (required)>'
Tasks: TOP => default => test
(See full trace by running task with --trace)
```

**Comment by flori** [comment]
Something is passing a -2 option to your ruby resulting in an "invalid option -2" error. Do you have a RUBYOPT environment variable set?

**Comment by bikeonastick** [comment]
robert.tomb@mybox:~/Development/mobile/appium-sample/sample-code/examples/ruby (master=)$ env |grep RUBY
RUBY_ENGINE=ruby
RUBY_ROOT=/Users/robert.tomb/.rubies/ruby-2.1.3
RUBYOPT=2.1.0
RUBY_VERSION=2.1.3
robert.tomb@mybox:~/Development/mobile/appium-sample/sample-code/examples/ruby (master=)$

well... this looks like it's being caused by the way chruby uses RUBYOPT! 

because in a shell where i have not run chruby, i have no RUBYOPT set:

robert.tomb@mybox:~/Development/mobile/appium-sample/sample-code/examples/ruby (master=)$ env | grep RUBY
robert.tomb@mybox:~/Development/mobile/appium-sample/sample-code/examples/ruby (master=)$

So, thanks for the suggestion. It's obvious that this is an issue with chruby and not with your build! I will close this.

**Comment by bikeonastick** [comment]
correction, it isn't chruby's fault, it was a user error (mine) while using chruby that is causing RUBYOPTS to be set.

**Comment by ngpestelos** [comment]
See also: https://github.com/postmodern/chruby/issues/255
