### ISSUE TITLE
JRuby ext does not handle objects without #to_json

### ISSUE THREAD

**Issue by headius** [flori/json#272]
This test fails on JRuby with the error shown. It seems a fix for this was not applied to the Java ext?

``` ruby
  def test_string_subclass
    s = Class.new(String) do
      def to_s; self; end
      undef to_json
    end
    assert_nothing_raised(SystemStackError) do
      assert_equal '[""]', JSON.generate([s.new])
    end
  end
```

Error:

```
TestJSONGenerate#test_string_subclass:
NoMethodError: undefined method `to_json' for "":#<Class:0x76ec39c2>
    json/ext/GeneratorState.java:210:in `generate'
    /Users/headius/projects/jruby/lib/ruby/stdlib/json/common.rb:223:in `generate'
    /Users/headius/projects/jruby/test/mri/json/test_json_generate.rb:345:in `block in test_string_subclass'
    /Users/headius/projects/jruby/test/mri/lib/test/unit/assertions.rb:171:in `assert_nothing_raised'
    /Users/headius/projects/jruby/test/mri/json/test_json_generate.rb:344:in `test_string_subclass'
```

**Comment by dafixa** [comment]
Is this being worked on?

**Comment by flori** [comment]
yes
