### ISSUE TITLE
JSON.parse fails when given a frozen ASCII-8BIT string in 2.0.1

### ISSUE THREAD

**Issue by backus** [flori/json#296]
```ruby
2.3.0 :004 > JSON.parse('{}'.force_encoding('ASCII-8BIT').freeze)
RuntimeError: can't modify frozen String
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/json-2.0.1/lib/json/common.rb:156:in `initialize'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/json-2.0.1/lib/json/common.rb:156:in `new'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/json-2.0.1/lib/json/common.rb:156:in `parse'
	from (irb):4
	from /Users/johnbackus/.rvm/rubies/ruby-2.3.0/bin/irb:11:in `<main>'
```

Cloneable example: https://gist.github.com/backus/b9b4c3df157041eeb2bf03adb357482c

**Comment by flori** [comment]
Should be fixed inversion 2.0.2.
