### ISSUE TITLE
JSON.parse returning unexpected value

### ISSUE THREAD

**Issue by ryannealmes** [flori/json#299]
We have been using JSON.parse for a while now and we just updated to the latest version.

We are getting the following error.

Has the functionality been updated to return `nil` instead of throwing a `ParserError`?

```ruby
2.3.0 :001 > gem 'json', '2.0.2'
 => true
2.3.0 :002 > require 'json'
 => true
2.3.0 :003 > JSON.parse("null")
 => nil

----------------------------------------------------------------------

2.3.0 :001 > gem 'json', '1.8.3'
 => true
2.3.0 :003 > require 'json'
 => true
2.3.0 :004 > JSON.parse("null")
JSON::ParserError: 784: unexpected token at 'null'
  from /Users/ryannealmes/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/json/common.rb:156:in `parse'
  from /Users/ryannealmes/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/json/common.rb:156:in `parse'
  from (irb):4
  from /Users/ryannealmes/.rvm/rubies/ruby-2.3.0/bin/irb:11:in `<main>'
2.3.0 :005 >
```

Thanks.

**Comment by ryannealmes** [comment]
Thanks I managed to find an answer here.

http://stackoverflow.com/questions/38669780/why-is-json-parse-not-throwing-exception
