### ISSUE TITLE
Ruby 2.4.0 & JSON 2.0.3 Segfault

### ISSUE THREAD

**Issue by bmurtagh** [flori/json#318]
`ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]`
installed JSON gem: `json (2.0.3, default: 2.0.2)`

I am using RVM and have Ruby 2.4.0 installed along with the latest json gem installed via `gem 'json', '~> 2.0', '>= 2.0.3'` in my `Gemfile`. I'm attempting to use `JSON.parse` and when my script executes, I am running into a segfault:

```
/Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/json-2.0.3/lib/json/ext/parser.bundle: [BUG] Segmentation fault
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/CrashReporter
     * /Library/Logs/CrashReporter
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   the more detail of.

-- Control frame information -----------------------------------------------
c:0014 p:-17548412065898 s:0058 e:000057 TOP    [FINISH]
c:0013 p:---- s:0056 e:000055 CFUNC  :require
c:0012 p:0115 s:0052 e:000051 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55
c:0011 p:0009 s:0042 e:000041 CLASS  /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/json-2.0.3/lib/json/ext.rb:7
c:0010 p:0011 s:0040 e:000039 CLASS  /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/json-2.0.3/lib/json/ext.rb:6
c:0009 p:0017 s:0038 e:000037 TOP    /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/json-2.0.3/lib/json/ext.rb:3 [FINISH]
c:0008 p:---- s:0036 e:000035 CFUNC  :require
c:0007 p:0115 s:0032 e:000031 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55
c:0006 p:0019 s:0022 e:000021 CLASS  /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/json-2.0.3/lib/json.rb:59
c:0005 p:0017 s:0020 e:000019 TOP    /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/json-2.0.3/lib/json.rb:55 [FINISH]
c:0004 p:---- s:0018 e:000017 CFUNC  :require
c:0003 p:0115 s:0014 e:000013 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55
c:0002 p:0015 s:0004 E:000468 EVAL   ./getJenkinsMetrics.rb:4 [FINISH]
c:0001 p:0000 s:0002 E:0025e8 TOP    [FINISH]

./getJenkinsMetrics.rb:4:in `<main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/json-2.0.3/lib/json.rb:55:in `<top (required)>'
/Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/json-2.0.3/lib/json.rb:59:in `<module:JSON>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/json-2.0.3/lib/json/ext.rb:3:in `<top (required)>'
/Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/json-2.0.3/lib/json/ext.rb:6:in `<module:JSON>'
/Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/json-2.0.3/lib/json/ext.rb:7:in `<module:Ext>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'

-- C level backtrace information -------------------------------------------

-- Other runtime information -----------------------------------------------

* Loaded script: ./getJenkinsMetrics.rb

* Loaded features:

    0 enumerator.so
    1 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/enc/encdb.bundle
    2 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/enc/trans/transdb.bundle
    3 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/rbconfig.rb
    4 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/compatibility.rb
    5 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/defaults.rb
    6 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/deprecate.rb
    7 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/errors.rb
    8 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/version.rb
    9 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/requirement.rb
   10 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/platform.rb
   11 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb
   12 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/exceptions.rb
   13 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb
   14 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/thread.rb
   15 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/monitor.rb
   16 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb
   17 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb
   18 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/path_support.rb
   19 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb
   20 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb
   21 /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/thor-0.19.4/lib/thor/command.rb
   22 /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/thor-0.19.4/lib/thor/core_ext/hash_with_indifferent_access.rb
   23 /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/thor-0.19.4/lib/thor/core_ext/ordered_hash.rb
   24 /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/thor-0.19.4/lib/thor/error.rb
   25 /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/thor-0.19.4/lib/thor/invocation.rb
   26 /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/thor-0.19.4/lib/thor/parser/argument.rb
   27 /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/thor-0.19.4/lib/thor/parser/arguments.rb
   28 /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/thor-0.19.4/lib/thor/parser/option.rb
   29 /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/thor-0.19.4/lib/thor/parser/options.rb
   30 /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/thor-0.19.4/lib/thor/parser.rb
   31 /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/thor-0.19.4/lib/thor/shell.rb
   32 /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/thor-0.19.4/lib/thor/line_editor/basic.rb
   33 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/readline.bundle
   34 /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/thor-0.19.4/lib/thor/line_editor/readline.rb
   35 /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/thor-0.19.4/lib/thor/line_editor.rb
   36 /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/thor-0.19.4/lib/thor/util.rb
   37 /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/thor-0.19.4/lib/thor/base.rb
   38 /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/thor-0.19.4/lib/thor.rb
   39 /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/json-2.0.3/lib/json/version.rb
   40 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/ostruct.rb
   41 /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/json-2.0.3/lib/json/generic_object.rb
   42 /Users/brendan/.rvm/gems/ruby-2.4.0@ruby-jenkins-metrics/gems/json-2.0.3/lib/json/common.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
Don't forget to include the above Crash Report log file.
For details: http://www.ruby-lang.org/bugreport.html

Abort trap: 6
```

**Comment by nomoon** [comment]
I'm having this issue with `rake assets:precompile` and I can't seem to find a workaround.

**Comment by bmurtagh** [comment]
@nomoon what helped me out was changing my shebang line from `/usr/bin/ruby` to `/usr/bin/env ruby`. Granted, I don't know if that'll help you, but from further discussion and asking around, it looks like my OSX ruby was being referenced `/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/` but the JSON gem and what my default Ruby should've been is `2.4.0`. Once I used `/usr/bin/env ruby`, things seem to fall in line.

**Comment by DNA** [comment]
Had the same problem here and it was also related to the 2.0 system ruby being referenced on a 2.4 gemset. A simple `gem pristine --all` fixed the problem 🙂
