### ISSUE TITLE
JSON.parse doesn't work with nested hashes (max_nested > 3)

### ISSUE THREAD

**Issue by faustoct** [flori/json#356]
The following code doesn't work as supposed to.. it should parse the string json normally and get a fully json as result

````
#the json
x = "{\"params\":{\"location\":\"{\"mocked\":false,\"timestamp\":1529077161691,\"coords\":{\"speed\":0,\"heading\":0,\"accuracy\":16,\"longitude\":-47.8464966,\"altitude\":0,\"latitude\":-24.5076421}}\"}}" 

$results in
puts JSON.parse(x)

Traceback (most recent call last):
       13: from /Users/fausto/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `<main>'
       12: from /Users/fausto/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `eval'
       11: from /Users/fausto/.rvm/gems/ruby-2.5.1/bin/padrino:23:in `<main>'
       10: from /Users/fausto/.rvm/gems/ruby-2.5.1/bin/padrino:23:in `load'
        9: from /Users/fausto/.rvm/gems/ruby-2.5.1/gems/padrino-core-0.14.2/bin/padrino:9:in `<top (required)>'
        8: from /Users/fausto/.rvm/gems/ruby-2.5.1/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        7: from /Users/fausto/.rvm/gems/ruby-2.5.1/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        6: from /Users/fausto/.rvm/gems/ruby-2.5.1/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        5: from /Users/fausto/.rvm/gems/ruby-2.5.1/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        4: from /Users/fausto/.rvm/gems/ruby-2.5.1/gems/padrino-core-0.14.2/lib/padrino-core/cli/base.rb:43:in `console'
        3: from (irb):15
        2: from /Users/fausto/.rvm/gems/ruby-2.5.1/gems/json_pure-2.1.0/lib/json/common.rb:156:in `parse'
        1: from /Users/fausto/.rvm/gems/ruby-2.5.1/gems/json_pure-2.1.0/lib/json/common.rb:156:in `parse'
JSON::ParserError (765: unexpected token at '{"params":{"location":"{"mocked":false,"timestamp":1529077161691,"coords":{"speed":0,"heading":0,"accuracy":16,"longitude":-47.8464966,"altitude":0,"latitude":-24.5076421}}"}}')
````

The following code used to work
````
x= "{\"params\":{\"location\":\"{\\\"mocked\\\":false,\\\"timestamp\\\":1529077161691,\\\"coords\\\":{\\\"speed\\\":0,\\\"heading\\\":0,\\\"accuracy\\\":16,\\\"longitude\\\":-47.8464966,\\\"altitude\\\":0,\\\"latitude\\\":-24.5076421}}\"}}"

#got
puts JSON.parse(x) 
{"params"=>{"location"=>"{"mocked":false,"timestamp":1529077161691,"coords":{"speed":0,"heading":0,"accuracy":16,"longitude":-47.8464966,"altitude":0,"latitude":-24.5076421}}}} 

````

Now I get this
````
{"params":{"location":"{\"mocked\":false,\"timestamp\":1529077161691,\"coords\":{\"speed\":0,\"heading\":0,\"accuracy\":16,\"longitude\":-47.8464966,\"altitude\":0,\"latitude\":-24.5076421}}"}}
````

@flori any idea?

**Comment by flori** [comment]
If the value of the location key should be a hash, don't make it a string in JSON:

    x = "{\"params\":{\"location\":{\"mocked\":false,\"timestamp\":1529077161691,\"coords\":{\"speed\":0,\"heading\":0,\"accuracy\":16,\"longitude\":-47.8464966,\"altitude\":0,\"latitude\":-24.5076421}}}}"

**Comment by faustoct** [comment]
@flori gonna try

**Comment by faustoct** [comment]
@flori making location a hash doesn't work
````
x = "{\"params\":{\"location\":{mocked:false,timestamp:1529077161691,coords:{speed:0,heading:0,accuracy:16,longitude:-47.8464966,altitude:0,latitude:-24.5076421}}}}"

Traceback (most recent call last):
       13: from /Users/fausto/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `<main>'
       12: from /Users/fausto/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `eval'
       11: from /Users/fausto/.rvm/gems/ruby-2.5.1/bin/padrino:23:in `<main>'
       10: from /Users/fausto/.rvm/gems/ruby-2.5.1/bin/padrino:23:in `load'
        9: from /Users/fausto/.rvm/gems/ruby-2.5.1/gems/padrino-core-0.14.2/bin/padrino:9:in `<top (required)>'
        8: from /Users/fausto/.rvm/gems/ruby-2.5.1/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        7: from /Users/fausto/.rvm/gems/ruby-2.5.1/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        6: from /Users/fausto/.rvm/gems/ruby-2.5.1/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        5: from /Users/fausto/.rvm/gems/ruby-2.5.1/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        4: from /Users/fausto/.rvm/gems/ruby-2.5.1/gems/padrino-core-0.14.2/lib/padrino-core/cli/base.rb:43:in `console'
        3: from (irb):7
        2: from /Users/fausto/.rvm/gems/ruby-2.5.1/gems/json-2.1.0/lib/json/common.rb:156:in `parse'
        1: from /Users/fausto/.rvm/gems/ruby-2.5.1/gems/json-2.1.0/lib/json/common.rb:156:in `parse'
JSON::ParserError (765: unexpected token at '{"params":{"location":{mocked:false,timestamp:1529077161691,coords:{speed:0,heading:0,accuracy:16,longitude:-47.8464966,altitude:0,latitude:-24.5076421}}}}')
````

**Comment by faustoct** [comment]
fixed it adding to my class will be executed before any request
````
    before do
      params.keys.each { |key|
        params[key.to_sym] = JSON.parse(params[key], :symbolize_names => true)
        params[key] = JSON.parse(params[key])
      }
    end
````
