### ISSUE TITLE
'stdio.h' file not found

### ISSUE THREAD

**Issue by nerychucuy** [flori/json#476]
Hi everyone :wave: 

I'm using [fastlane](https://github.com/fastlane/fastlane) on Github Actions which depends on this package. Today I had to set a fixed version of Swift = 5.4.3 and after that I started getting this error. Any ideas?  Thank you!

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/usr/local/lib/ruby/gems/2.7.0/gems/json-2.5.1/ext/json/ext/generator
/usr/local/opt/ruby@2.7/bin/ruby -I /usr/local/lib/ruby/site_ruby/2.7.0 -r
./siteconf20210925-5539-185ktw5.rb extconf.rb
creating Makefile

current directory:
/usr/local/lib/ruby/gems/2.7.0/gems/json-2.5.1/ext/json/ext/generator
make DESTDIR\= clean

current directory:
/usr/local/lib/ruby/gems/2.7.0/gems/json-2.5.1/ext/json/ext/generator
make DESTDIR\=
compiling generator.c
In file included from generator.c:1:
In file included from ./../fbuffer/fbuffer.h:5:
In file included from
/usr/local/Cellar/ruby@2.7/2.7.4/include/ruby-2.7.0/ruby.h:33:
In file included from
/usr/local/Cellar/ruby@2.7/2.7.4/include/ruby-2.7.0/ruby/ruby.h:29:
/usr/local/Cellar/ruby@2.7/2.7.4/include/ruby-2.7.0/ruby/defines.h:126:10: fatal
error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
1 error generated.
make: *** [generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in
/usr/local/lib/ruby/gems/2.7.0/gems/json-2.5.1 for inspection.
Results logged to
/usr/local/lib/ruby/gems/2.7.0/extensions/x86_64-darwin-19/2.7.0/json-2.5.1/gem_make.out

  /usr/local/lib/ruby/site_ruby/2.7.0/rubygems/ext/builder.rb:92:in `run'
/usr/local/lib/ruby/site_ruby/2.7.0/rubygems/ext/builder.rb:43:in `block in
make'
  /usr/local/lib/ruby/site_ruby/2.7.0/rubygems/ext/builder.rb:35:in `each'
  /usr/local/lib/ruby/site_ruby/2.7.0/rubygems/ext/builder.rb:35:in `make'
/usr/local/lib/ruby/site_ruby/2.7.0/rubygems/ext/ext_conf_builder.rb:63:in
`block in build'
  /usr/local/Cellar/ruby@2.7/2.7.4/lib/ruby/2.7.0/tempfile.rb:291:in `open'
/usr/local/lib/ruby/site_ruby/2.7.0/rubygems/ext/ext_conf_builder.rb:26:in
`build'
/usr/local/lib/ruby/site_ruby/2.7.0/rubygems/ext/builder.rb:158:in
`build_extension'
/usr/local/lib/ruby/site_ruby/2.7.0/rubygems/ext/builder.rb:192:in `block in
build_extensions'
  /usr/local/lib/ruby/site_ruby/2.7.0/rubygems/ext/builder.rb:189:in `each'
/usr/local/lib/ruby/site_ruby/2.7.0/rubygems/ext/builder.rb:189:in
`build_extensions'
/usr/local/lib/ruby/site_ruby/2.7.0/rubygems/installer.rb:837:in
`build_extensions'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.27/lib/bundler/rubygems_gem_installer.rb:66:in
`build_extensions'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.27/lib/bundler/rubygems_gem_installer.rb:26:in
`install'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.27/lib/bundler/source/rubygems.rb:199:in
`install'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.27/lib/bundler/installer/gem_installer.rb:54:in
`install'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.27/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.27/lib/bundler/installer/parallel_installer.rb:186:in
`do_install'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.27/lib/bundler/installer/parallel_installer.rb:177:in
`block in worker_pool'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.27/lib/bundler/worker.rb:62:in
`apply_func'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.27/lib/bundler/worker.rb:57:in
`block in process_queue'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.27/lib/bundler/worker.rb:54:in
`loop'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.27/lib/bundler/worker.rb:54:in
`process_queue'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.27/lib/bundler/worker.rb:91:in
`block (2 levels) in create_threads'

An error occurred while installing json (2.5.1), and Bundler cannot continue.

In Gemfile:
  fastlane was resolved to 2.195.0, which depends on
    json
```

**Comment by nerychucuy** [comment]
Update: in case anyone needs to know this, the problem was that in order to use Swift = 5.4.3, I had to use Xcode command line tools 12.5.1, see this thread for further info: https://github.com/fastlane/fastlane/issues/19384 .
