### ISSUE TITLE
wrong number of arguments (given 2, expected 1) (ArgumentError)

### ISSUE THREAD

**Issue by Legomegger** [flori/json#487]
Hello, other gem requires this json gem, and I got this error
```
/Users/ascaroff/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/json-1.8.6/lib/json/common.rb:155:in `initialize': wrong number of arguments (given 2, expected 1) (ArgumentError)
        from /Users/ascaroff/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/json-1.8.6/lib/json/common.rb:155:in `new'
        from /Users/ascaroff/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/json-1.8.6/lib/json/common.rb:155:in `parse'
        from /Users/ascaroff/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/compile_cache/json.rb:48:in `init!'
        from /Users/ascaroff/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/compile_cache/json.rb:36:in `install!'
        from /Users/ascaroff/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/compile_cache.rb:29:in `setup'
        from /Users/ascaroff/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap.rb:70:in `setup'
        from /Users/ascaroff/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap.rb:112:in `default_setup'
        from /Users/ascaroff/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/setup.rb:4:in `<top (required)>'
        from /Users/ascaroff/work/powr-3/config/boot.rb:4:in `require'
        from /Users/ascaroff/work/powr-3/config/boot.rb:4:in `<top (required)>'
        from bin/rails:3:in `require_relative'
        from bin/rails:3:in `<main>'
```
Using ruby 3.0.2

this is the usage
 ```
 def parse(source, opts = {})
    Parser.new(source, opts).parse
  end
```
args
```
"[\"foo\"]" # source
{:freeze=>true} # opts
```

**Comment by hsbt** [comment]
Your `json` version is too old. Use json-2.5.0+.
