### ISSUE TITLE
json-1.8.6/lib/json/common.rb:155:in `initialize': wrong number of arguments (given 2, expected 1) (ArgumentError)

### ISSUE THREAD

**Issue by kashiftufail** [flori/json#542]
Hello!
My app is runnung on Rails 7.0.8 with Ruby version 2.7.1. When i update Ruby to 3.0.0, i received this error. 

       /home/lap-053/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/json-1.8.6/lib/json/common.rb:155:in `initialize': wrong number of arguments (given 2, expected 1) (ArgumentError)

all trace is below

/home/lap-053/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/json-1.8.6/lib/json/common.rb:155:in `initialize': wrong number of arguments (given 2, expected 1) (ArgumentError)
	from /home/lap-053/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/json-1.8.6/lib/json/common.rb:155:in `new'
	from /home/lap-053/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/json-1.8.6/lib/json/common.rb:155:in `parse'
	from /home/lap-053/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/jmespath-1.6.2/lib/jmespath/lexer.rb:323:in `requires_wrapping?'
	from /home/lap-053/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/jmespath-1.6.2/lib/jmespath/lexer.rb:328:in `<class:Lexer>'
	from /home/lap-053/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/jmespath-1.6.2/lib/jmespath/lexer.rb:7:in `<module:JMESPath>'
	from /home/lap-053/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/jmespath-1.6.2/lib/jmespath/lexer.rb:5:in `<top (required)>'
	from /home/lap-053/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/jmespath-1.6.2/lib/jmespath.rb:9:in `require'
	from /home/lap-053/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/jmespath-1.6.2/lib/jmespath.rb:9:in `<module:JMESPath>'
	from /home/lap-053/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/jmespath-1.6.2/lib/jmespath.rb:6:in `<top (required)>'
	from /home/lap-053/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/aws-sdk-core-3.183.0/lib/aws-sdk-core.rb:5:in `require'
	from /home/lap-053/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/aws-sdk-core-3.183.0/lib/aws-sdk-core.rb:5:in `<top (required)>'
	from /home/lap-053/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/aws-sdk-kms-1.71.0/lib/aws-sdk-kms.rb:11:in `require'
	from /home/lap-053/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/aws-sdk-kms-1.71.0/lib/aws-sdk-kms.rb:11:in `<top (required)>'
	from /home/lap-053/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/aws-sdk-s3-1.135.0/lib/aws-sdk-s3.rb:11:in `require'
	from /home/lap-053/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/aws-sdk-s3-1.135.0/lib/aws-sdk-s3.rb:11:in `<top (required)>'
	from /home/lap-053/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.3.4/lib/bundler/runtime.rb:60:in `require'
	from /home/lap-053/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.3.4/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
	from /home/lap-053/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.3.4/lib/bundler/runtime.rb:55:in `each'
	from /home/lap-053/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.3.4/lib/bundler/runtime.rb:55:in `block in require'
	from /home/lap-053/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.3.4/lib/bundler/runtime.rb:44:in `each'
	from /home/lap-053/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.3.4/lib/bundler/runtime.rb:44:in `require'
	from /home/lap-053/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.3.4/lib/bundler.rb:176:in `require'
	from /home/lap-053/rails/mainwebsite/config/application.rb:7:in `<top (required)>'
	from /home/lap-053/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-7.0.8/lib/rails/commands/server/server_command.rb:137:in `require'
	from /home/lap-053/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-7.0.8/lib/rails/commands/server/server_command.rb:137:in `block in perform'
	from <internal:kernel>:90:in `tap'
	from /home/lap-053/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-7.0.8/lib/rails/commands/server/server_command.rb:134:in `perform'
	from /home/lap-053/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
	from /home/lap-053/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/lap-053/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
	from /home/lap-053/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-7.0.8/lib/rails/command/base.rb:87:in `perform'
	from /home/lap-053/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-7.0.8/lib/rails/command.rb:48:in `invoke'
	from /home/lap-053/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-7.0.8/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'

My gemfile.lock is 

        GIT
  remote: https://github.com/tcocca/acts_as_follower.git
  revision: c5ac7b9601c4af01eb4d9112330b27be4d694ecc
  specs:
    acts_as_follower (0.2.1)
      activerecord (>= 4.0)

GEM
  remote: https://rubygems.org/
  specs:
    actioncable (7.0.8)
      actionpack (= 7.0.8)
      activesupport (= 7.0.8)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailbox (7.0.8)
      actionpack (= 7.0.8)
      activejob (= 7.0.8)
      activerecord (= 7.0.8)
      activestorage (= 7.0.8)
      activesupport (= 7.0.8)
      mail (>= 2.7.1)
      net-imap
      net-pop
      net-smtp
    actionmailer (7.0.8)
      actionpack (= 7.0.8)
      actionview (= 7.0.8)
      activejob (= 7.0.8)
      activesupport (= 7.0.8)
      mail (~> 2.5, >= 2.5.4)
      net-imap
      net-pop
      net-smtp
      rails-dom-testing (~> 2.0)
    actionpack (7.0.8)
      actionview (= 7.0.8)
      activesupport (= 7.0.8)
      rack (~> 2.0, >= 2.2.4)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.2.0)
    actiontext (7.0.8)
      actionpack (= 7.0.8)
      activerecord (= 7.0.8)
      activestorage (= 7.0.8)
      activesupport (= 7.0.8)
      globalid (>= 0.6.0)
      nokogiri (>= 1.8.5)
    actionview (7.0.8)
      activesupport (= 7.0.8)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.1, >= 1.2.0)
    active_material (1.5.2)
    activeadmin (2.11.2)
      arbre (~> 1.2, >= 1.2.1)
      formtastic (>= 3.1, < 5.0)
      formtastic_i18n (~> 0.4)
      inherited_resources (~> 1.7)
      jquery-rails (~> 4.2)
      kaminari (~> 1.0, >= 1.2.1)
      railties (>= 6.0, < 7.1)
      ransack (~> 2.1, >= 2.1.1)
    activeadmin-ajax_filter (0.7.0)
      activeadmin (>= 1.0)
      coffee-rails (>= 4.1.0)
      rails (>= 7.0)
      selectize-rails (>= 0.12.6)
    activeadmin_addons (1.10.1)
      active_material
      railties
      redcarpet
      require_all
      sassc
      sassc-rails
      xdan-datetimepicker-rails (~> 2.5.1)
    activejob (7.0.8)
      activesupport (= 7.0.8)
      globalid (>= 0.3.6)
    activemodel (7.0.8)
      activesupport (= 7.0.8)
    activerecord (7.0.8)
      activemodel (= 7.0.8)
      activesupport (= 7.0.8)
    activestorage (7.0.8)
      actionpack (= 7.0.8)
      activejob (= 7.0.8)
      activerecord (= 7.0.8)
      activesupport (= 7.0.8)
      marcel (~> 1.0)
      mini_mime (>= 1.1.0)
    activesupport (7.0.8)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
    acts-as-taggable-on (9.0.1)
      activerecord (>= 6.0, < 7.1)
    acts_as_list (1.1.0)
      activerecord (>= 4.2)
    acts_as_votable (0.12.1)
    addressable (2.8.5)
      public_suffix (>= 2.0.2, < 6.0)
    airbrake (13.0.3)
      airbrake-ruby (~> 6.0)
    airbrake-ruby (6.2.1)
      rbtree3 (~> 0.6)
    anchored (1.1.0)
    ansi (1.5.0)
    arbre (1.6.0)
      activesupport (>= 3.0.0, < 7.1)
      ruby2_keywords (>= 0.0.2, < 1.0)
    arctic_admin (4.2.5)
      activeadmin (>= 1.1.0, < 4.0)
      font-awesome-sass (~> 6.0)
    asset_sync (2.19.1)
      activemodel (>= 4.1.0)
      fog-core
      mime-types (>= 2.99)
      unf
    ast (2.4.2)
    autocomplete-activeadmin (0.1.0)
      rails (>= 3.2)
    autoprefixer-rails (10.4.15.0)
      execjs (~> 2)
    aws-eventstream (1.2.0)
    aws-partitions (1.826.0)
    aws-sdk (1.67.0)
      aws-sdk-v1 (= 1.67.0)
    aws-sdk-core (3.183.0)
      aws-eventstream (~> 1, >= 1.0.2)
      aws-partitions (~> 1, >= 1.651.0)
      aws-sigv4 (~> 1.5)
      jmespath (~> 1, >= 1.6.1)
    aws-sdk-kms (1.71.0)
      aws-sdk-core (~> 3, >= 3.177.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-s3 (1.135.0)
      aws-sdk-core (~> 3, >= 3.181.0)
      aws-sdk-kms (~> 1)
      aws-sigv4 (~> 1.6)
    aws-sdk-v1 (1.67.0)
      json (~> 1.4)
      nokogiri (~> 1)
    aws-sigv4 (1.6.0)
      aws-eventstream (~> 1, >= 1.0.2)
    bcrypt (3.1.19)
    bigdecimal (1.3.5)
    bindex (0.8.1)
    bootstrap (5.3.1)
      autoprefixer-rails (>= 9.1.0)
      popper_js (>= 2.11.8, < 3)
      sassc-rails (>= 2.0.0)
    bootstrap-chosen-rails (0.0.4)
    browser (5.3.1)
    bson (4.15.0)
    builder (3.2.4)
    byebug (11.1.3)
    cancancan (3.5.0)
    capybara (3.39.2)
      addressable
      matrix
      mini_mime (>= 0.1.3)
      nokogiri (~> 1.8)
      rack (>= 1.6.0)
      rack-test (>= 0.6.3)
      regexp_parser (>= 1.5, < 3.0)
      xpath (~> 3.2)
    capybara-email (3.0.2)
      capybara (>= 2.4, < 4.0)
      mail
    carrierwave (3.0.3)
      activemodel (>= 6.0.0)
      activesupport (>= 6.0.0)
      addressable (~> 2.6)
      image_processing (~> 1.1)
      marcel (~> 1.0.0)
      ssrf_filter (~> 1.0)
    chartkick (5.0.4)
    childprocess (4.1.0)
    chosen-rails (1.10.0)
      coffee-rails (>= 3.2)
      railties (>= 3.0)
      sassc-rails (>= 2.1.2)
    chronic (0.10.2)
    cocoon (1.2.15)
    coderay (1.1.3)
    coffee-rails (5.0.0)
      coffee-script (>= 2.2.0)
      railties (>= 5.2.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.12.2)
    concurrent-ruby (1.2.2)
    connection_pool (2.4.1)
    cookies_eu (1.7.8)
      js_cookie_rails (~> 2.2.0)
    crass (1.0.6)
    data-confirm-modal (1.6.3)
      railties (>= 3.0)
    database_cleaner (2.0.2)
      database_cleaner-active_record (>= 2, < 3)
    database_cleaner-active_record (2.1.0)
      activerecord (>= 5.a)
      database_cleaner-core (~> 2.0.0)
    database_cleaner-core (2.0.1)
    date (3.3.3)
    devise (4.9.2)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0)
      responders
      warden (~> 1.2.3)
    devise-security (0.18.0)
      devise (>= 4.3.0)
    diff-lcs (1.5.0)
    dotenv (2.8.1)
    dotenv-rails (2.8.1)
      dotenv (= 2.8.1)
      railties (>= 3.2)
    erubi (1.12.0)
    et-orbi (1.2.7)
      tzinfo
    ethon (0.16.0)
      ffi (>= 1.15.0)
    excon (0.103.0)
    execjs (2.9.1)
    factory_bot (6.2.1)
      activesupport (>= 5.0.0)
    factory_bot_rails (6.2.0)
      factory_bot (~> 6.2.0)
      railties (>= 5.0.0)
    faker (2.19.0)
      i18n (>= 1.6, < 2)
    ffi (1.15.5)
    fog-aws (3.19.0)
      fog-core (~> 2.1)
      fog-json (~> 1.1)
      fog-xml (~> 0.1)
    fog-core (2.3.0)
      builder
      excon (~> 0.71)
      formatador (>= 0.2, < 2.0)
      mime-types
    fog-json (1.2.0)
      fog-core
      multi_json (~> 1.10)
    fog-xml (0.1.4)
      fog-core
      nokogiri (>= 1.5.11, < 2.0.0)
    font-awesome-rails (4.7.0.8)
      railties (>= 3.2, < 8.0)
    font-awesome-sass (6.4.2)
      sassc (~> 2.0)
    font_awesome5_rails (1.5.0)
      nokogiri (>= 1.11.3)
      railties (>= 4.2)
    formatador (1.1.0)
    formtastic (4.0.0)
      actionpack (>= 5.2.0)
    formtastic_i18n (0.7.0)
    friendly_id (5.5.0)
      activerecord (>= 4.0.0)
    fugit (1.8.1)
      et-orbi (~> 1, >= 1.2.7)
      raabro (~> 1.4)
    geocoder (1.8.2)
    geocomplete_rails (1.7.0)
      railties (>= 3.1)
    globalid (1.2.1)
      activesupport (>= 6.1)
    has_scope (0.8.1)
      actionpack (>= 5.2)
      activesupport (>= 5.2)
    httparty (0.21.0)
      mini_mime (>= 1.0.0)
      multi_xml (>= 0.5.2)
    i18n (1.14.1)
      concurrent-ruby (~> 1.0)
    image_info (1.2.2)
      addressable (~> 2.0)
      image_size (~> 2.0)
      typhoeus (~> 1.0)
    image_processing (1.12.2)
      mini_magick (>= 4.9.5, < 5)
      ruby-vips (>= 2.0.17, < 3)
    image_size (2.1.2)
    inherited_resources (1.13.1)
      actionpack (>= 5.2, < 7.1)
      has_scope (~> 0.6)
      railties (>= 5.2, < 7.1)
      responders (>= 2, < 4)
    iso8601 (0.13.0)
    jbuilder (2.11.5)
      actionview (>= 5.0.0)
      activesupport (>= 5.0.0)
    jmespath (1.6.2)
    jquery-datetimepicker-rails (2.4.1.0)
    jquery-fileupload-rails (0.4.7)
      actionpack (>= 3.1)
      railties (>= 3.1)
      sass (>= 3.2)
    jquery-infinite-pages (0.2.0)
      coffee-script
      jquery-rails
      railties (>= 3.1)
    jquery-inputmask-rails (2.5.5)
    jquery-rails (4.6.0)
      rails-dom-testing (>= 1, < 3)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    jquery-ui-rails (6.0.1)
      railties (>= 3.2.16)
    js_cookie_rails (2.2.0)
      railties (>= 3.1)
    json (1.8.6)
    kaminari (1.2.2)
      activesupport (>= 4.1.0)
      kaminari-actionview (= 1.2.2)
      kaminari-activerecord (= 1.2.2)
      kaminari-core (= 1.2.2)
    kaminari-actionview (1.2.2)
      actionview
      kaminari-core (= 1.2.2)
    kaminari-activerecord (1.2.2)
      activerecord
      kaminari-core (= 1.2.2)
    kaminari-core (1.2.2)
    launchy (2.5.2)
      addressable (~> 2.8)
    letter_opener (1.8.1)
      launchy (>= 2.2, < 3)
    link_thumbnailer (3.4.0)
      activesupport (>= 3.0)
      image_info (~> 1.0, >= 1.2.0)
      json (>= 1.7.7)
      net-http-persistent (>= 2.9)
      nokogiri (>= 1.6)
      rake (>= 0.9)
      video_info (>= 2.6)
    listen (3.4.1)
      rb-fsevent (~> 0.10, >= 0.10.3)
      rb-inotify (~> 0.9, >= 0.9.10)
    lockup (1.7)
      rails (>= 3, < 7.1)
    loofah (2.21.3)
      crass (~> 1.0.2)
      nokogiri (>= 1.12.0)
    mail (2.8.1)
      mini_mime (>= 0.1.1)
      net-imap
      net-pop
      net-smtp
    marcel (1.0.2)
    matrix (0.4.2)
    maxminddb (0.1.22)
    mention_system (0.3.1)
      rails (>= 6.0)
    meta-tags (2.18.0)
      actionpack (>= 3.2.0, < 7.1)
    method_source (1.0.0)
    mime-types (3.5.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2023.0808)
    mimemagic (0.4.3)
      nokogiri (~> 1)
      rake
    mini_magick (4.12.0)
    mini_mime (1.1.5)
    mini_portile2 (2.8.4)
    minitest (5.20.0)
    mongo (2.19.1)
      bson (>= 4.14.1, < 5.0.0)
    mongoid (7.3.5)
      activemodel (>= 5.1, < 7.1, != 7.0.0)
      mongo (>= 2.10.5, < 3.0.0)
      ruby2_keywords (~> 0.0.5)
    multi_json (1.15.0)
    multi_xml (0.6.0)
    nested_form_fields (0.8.4)
      coffee-rails (>= 3.2.1)
      jquery-rails
      rails (>= 3.2.0)
    net-http-persistent (4.0.2)
      connection_pool (~> 2.2)
    net-imap (0.3.7)
      date
      net-protocol
    net-pop (0.1.2)
      net-protocol
    net-protocol (0.2.1)
      timeout
    net-smtp (0.4.0)
      net-protocol
    net_http_timeout_errors (1.0.0)
    nio4r (2.5.9)
    nokogiri (1.15.4)
      mini_portile2 (~> 2.8.2)
      racc (~> 1.4)
    nokogiri (1.15.4-x86_64-linux)
      racc (~> 1.4)
    oga (3.4)
      ast
      ruby-ll (~> 2.1)
    orm_adapter (0.5.0)
    owlcarousel-rails (2.2.3.5)
    paper_trail (12.2.0)
      activerecord (>= 5.2)
      request_store (~> 1.1)
    paper_trail-association_tracking (2.2.1)
      paper_trail (>= 12.0)
    paper_trail-globalid (0.2.0)
      globalid
      paper_trail (>= 3.0.0)
    parallel (1.23.0)
    parallel_tests (3.13.0)
      parallel
    pg (1.5.4)
    popper_js (2.11.8)
    pry (0.14.2)
      coderay (~> 1.1)
      method_source (~> 1.0)
    public_suffix (5.0.3)
    puma (5.6.7)
      nio4r (~> 2.0)
    raabro (1.4.0)
    racc (1.7.1)
    rack (2.2.8)
    rack-proxy (0.7.7)
      rack
    rack-test (2.1.0)
      rack (>= 1.3)
    rails (7.0.8)
      actioncable (= 7.0.8)
      actionmailbox (= 7.0.8)
      actionmailer (= 7.0.8)
      actionpack (= 7.0.8)
      actiontext (= 7.0.8)
      actionview (= 7.0.8)
      activejob (= 7.0.8)
      activemodel (= 7.0.8)
      activerecord (= 7.0.8)
      activestorage (= 7.0.8)
      activesupport (= 7.0.8)
      bundler (>= 1.15.0)
      railties (= 7.0.8)
    rails-dom-testing (2.2.0)
      activesupport (>= 5.0.0)
      minitest
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.6.0)
      loofah (~> 2.21)
      nokogiri (~> 1.14)
    rails-jquery-autocomplete (1.0.5)
      rails (>= 3.2)
    rails_exception_handler (2.4.7)
    railties (7.0.8)
      actionpack (= 7.0.8)
      activesupport (= 7.0.8)
      method_source
      rake (>= 12.2)
      thor (~> 1.0)
      zeitwerk (~> 2.5)
    rake (13.0.6)
    ransack (2.6.0)
      activerecord (>= 6.0.4)
      activesupport (>= 6.0.4)
      i18n
    rb-fsevent (0.11.2)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    rbtree3 (0.7.1)
    recaptcha (5.15.0)
    redcarpet (3.6.0)
    redis (4.2.5)
    regexp_parser (2.8.1)
    request_store (1.5.1)
      rack (>= 1.4)
    require_all (3.0.0)
    responders (3.1.0)
      actionpack (>= 5.2)
      railties (>= 5.2)
    rexml (3.2.6)
    rspec-core (3.12.2)
      rspec-support (~> 3.12.0)
    rspec-expectations (3.12.3)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.12.0)
    rspec-mocks (3.12.6)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.12.0)
    rspec-rails (6.0.3)
      actionpack (>= 6.1)
      activesupport (>= 6.1)
      railties (>= 6.1)
      rspec-core (~> 3.12)
      rspec-expectations (~> 3.12)
      rspec-mocks (~> 3.12)
      rspec-support (~> 3.12)
    rspec-support (3.12.1)
    ruby-ll (2.1.3)
      ansi
      ast
    ruby-vips (2.1.4)
      ffi (~> 1.12)
    ruby2_keywords (0.0.5)
    rubyzip (2.3.2)
    rufus-scheduler (3.9.1)
      fugit (~> 1.1, >= 1.1.6)
    s3_direct_upload (0.1.7)
      coffee-rails (>= 3.1)
      jquery-fileupload-rails (~> 0.4.1)
      rails (>= 3.1)
      sass-rails (>= 3.1)
    sass (3.7.4)
      sass-listen (~> 4.0.0)
    sass-listen (4.0.0)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    sass-rails (5.1.0)
      railties (>= 5.2.0)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    sassc (2.4.0)
      ffi (~> 1.9)
    sassc-rails (2.1.2)
      railties (>= 4.0.0)
      sassc (>= 2.0)
      sprockets (> 3.0)
      sprockets-rails
      tilt
    select2-rails (4.0.13)
    selectize-rails (0.12.6)
    selenium-webdriver (4.6.1)
      childprocess (>= 0.5, < 5.0)
      rexml (~> 3.2, >= 3.2.5)
      rubyzip (>= 1.2.2, < 3.0)
      websocket (~> 1.0)
    semantic_range (3.0.0)
    shortener (1.0.1)
      voight_kampff (~> 2.0)
    shoulda-callback-matchers (1.1.4)
      activesupport (>= 3)
    shoulda-matchers (5.3.0)
      activesupport (>= 5.2.0)
    sidekiq (6.2.2)
      connection_pool (>= 2.2.2)
      rack (~> 2.0)
      redis (>= 4.2.0)
    sidekiq-scheduler (5.0.3)
      rufus-scheduler (~> 3.2)
      sidekiq (>= 6, < 8)
      tilt (>= 1.4.0)
    simple_form (5.2.0)
      actionpack (>= 5.2)
      activemodel (>= 5.2)
    sitemap_generator (6.3.0)
      builder (~> 3.0)
    social-share-button (1.2.4)
      coffee-rails
    spring (1.7.2)
    spring-watcher-listen (2.0.1)
      listen (>= 2.7, < 4.0)
      spring (>= 1.2, < 3.0)
    sprockets (3.7.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.1.1)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    ssrf_filter (1.1.2)
    telesign (2.2.4)
      net-http-persistent (>= 3.0.0, < 5.0)
    thor (1.2.2)
    tilt (2.3.0)
    timeout (0.4.0)
    tribute (3.6.0.0)
    turbolinks (5.2.1)
      turbolinks-source (~> 5.2)
    turbolinks-source (5.2.0)
    typhoeus (1.4.0)
      ethon (>= 0.9.0)
    tzinfo (2.0.6)
      concurrent-ruby (~> 1.0)
    uglifier (4.2.0)
      execjs (>= 0.3.0, < 3)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.8.2)
    video_info (4.0.0)
      iso8601 (~> 0.13.0)
      net_http_timeout_errors (~> 1.0.0)
      oga (~> 3.4)
    voight_kampff (2.0.0)
      rack (>= 1.4)
    warden (1.2.9)
      rack (>= 2.0.9)
    web-console (4.2.1)
      actionview (>= 6.0.0)
      activemodel (>= 6.0.0)
      bindex (>= 0.4.0)
      railties (>= 6.0.0)
    webpacker (5.4.4)
      activesupport (>= 5.2)
      rack-proxy (>= 0.6.1)
      railties (>= 5.2)
      semantic_range (>= 2.3.0)
    websocket (1.2.10)
    websocket-driver (0.7.6)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    whenever (1.0.0)
      chronic (>= 0.6.3)
    xdan-datetimepicker-rails (2.5.4)
      jquery-rails
      rails (>= 3.2.16)
    xpath (3.2.0)
      nokogiri (~> 1.8)
    zeitwerk (2.6.11)
    zip-codes (0.2.1)

PLATFORMS
  ruby
  x86_64-linux

DEPENDENCIES
  activeadmin (~> 2.11.1)
  activeadmin-ajax_filter
  activeadmin_addons
  acts-as-taggable-on (~> 9.0.0)
  acts_as_follower!
  acts_as_list
  acts_as_votable (~> 0.12.0)
  airbrake
  anchored
  arctic_admin
  asset_sync
  autocomplete-activeadmin
  aws-sdk (< 2.0)
  aws-sdk-s3
  bigdecimal (= 1.3.5)
  bootstrap
  bootstrap-chosen-rails
  browser
  byebug
  cancancan
  capybara (>= 2.15)
  capybara-email
  carrierwave
  chartkick
  chosen-rails
  cocoon
  coffee-rails (~> 5.0.0)
  cookies_eu
  data-confirm-modal
  database_cleaner
  devise
  devise-security
  dotenv-rails
  factory_bot_rails
  faker (~> 2.19.0)
  fog-aws
  font-awesome-rails
  font_awesome5_rails
  friendly_id (~> 5.1)
  geocoder
  geocomplete_rails
  httparty
  jbuilder (~> 2.5)
  jquery-datetimepicker-rails
  jquery-infinite-pages
  jquery-inputmask-rails
  jquery-rails
  jquery-ui-rails
  letter_opener
  link_thumbnailer
  listen (~> 3.4.0)
  lockup (~> 1.6, >= 1.6.1)
  maxminddb
  mention_system (~> 0.3.0)
  meta-tags
  mimemagic (~> 0.4.3)
  mini_magick
  mongoid (~> 7.3.5)
  multi_json (~> 1.11, >= 1.11.2)
  nested_form_fields
  owlcarousel-rails
  paper_trail (~> 12.2.0)
  paper_trail-association_tracking
  paper_trail-globalid
  parallel_tests (~> 3.12, >= 3.12.1)
  pg (>= 0.18, < 2.0)
  popper_js
  pry
  puma (~> 5.6)
  rails (~> 7.0.1)
  rails-jquery-autocomplete
  rails_exception_handler (~> 2)
  recaptcha
  redis (~> 4.2.1)
  rspec-rails
  rubyzip
  s3_direct_upload
  sass-rails (~> 5.0)
  select2-rails
  selenium-webdriver (~> 4.6.1)
  shortener
  shoulda-callback-matchers
  shoulda-matchers
  sidekiq (~> 6.2.1)
  sidekiq-scheduler
  simple_form
  sitemap_generator
  social-share-button
  spring (~> 1.7.2)
  spring-watcher-listen (~> 2.0.0)
  sprockets-rails (~> 3.1.0)
  telesign
  tribute
  turbolinks (~> 5)
  tzinfo-data
  uglifier (>= 1.3.0)
  web-console
  webpacker
  whenever
  zip-codes (~> 0.2.1)

RUBY VERSION
   ruby 3.0.0p0

BUNDLED WITH
   2.3.4
    
In application.rb line no 7

           Bundler.require(*Rails.groups)

this code also i have in my intializer, but still above error

# config/initializers/json.rb
                module JSON
                  module_function

                 def parse(source, opts = {})
                   Parser.new(source, **opts).parse
                end
              end
Any help please.

Thanks

**Comment by kashiftufail** [comment]
I just update version of aws-sdk gem. after this latest version installed of json gem.

Now working fine!
